# Both types of tests work. Just pick one
.PHONY: tests
tests:
	PYTHONPATH=MyApp python -m unittest discover
#	PYTHONPATH=MyApp nosetests

verbose_tests:
	PYTHONPATH=MyApp python -m unittest discover -v
